version: "3.9"

services:
  spring-boot-app:
    build:
      context: ./backend
    ports:
      - "7000:7000"  
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:1234/mydb  
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql
  react-app:
    build:
      context: ./frontend 
    ports:
      - "2000:80"
    restart: always
    depends_on:
      - spring-boot-app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: hotel-db
    ports:
      - "1234:3306"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
