package backend.models.core;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.UuidGenerator;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import backend.models.enums.GiftCardStatus;

import java.time.Instant;
import java.util.UUID;

@Entity
@Getter
@Setter
@NoArgsConstructor
@Table(name = "gift_cards", indexes = {
        @Index(name = "idx_gift_card_code",          columnList = "code", unique = true),
        @Index(name = "idx_gift_card_purchased_by",  columnList = "purchased_by_user_id"),
        @Index(name = "idx_gift_card_order_item",    columnList = "purchased_on_order_item_id"),
        // Per-unit issuance guard: at most one card per (order item, unit ordinal). Rows with a
        // null order-item id (e.g. admin-issued cards) are exempt — NULLs are distinct in a unique
        // index — so this only constrains order-driven issuance.
        @Index(name = "uq_gift_card_order_item_unit",
               columnList = "purchased_on_order_item_id, unit_index", unique = true)
})
@EntityListeners(AuditingEntityListener.class)
public class GiftCard {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.TIME)
    @Column(columnDefinition = "BINARY(16)")
    private UUID id;

    @Version
    @Column(nullable = false)
    private Long version;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "company_id", nullable = false)
    private Company company;

    /**
     * 16-char uppercase alphanumeric code generated by SecureRandom.
     * Stored and compared case-insensitively; has a unique index.
     */
    @Column(nullable = false, length = 16, unique = true)
    private String code;

    @Column(nullable = false)
    private long originalValueCents;

    @Column(nullable = false)
    private long remainingBalanceCents;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "purchased_by_user_id", nullable = false)
    private User purchasedByUser;

    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "redeemed_by_user_id", nullable = true)
    private User redeemedByUser;

    /** Loose FK to orders.id — the order that triggered this card's issuance. */
    @Column(nullable = true, columnDefinition = "BINARY(16)")
    private UUID purchasedOnOrderId;

    /** Loose FK to order_items.id — used as idempotency key in issueCardsForOrder. */
    @Column(nullable = true, columnDefinition = "BINARY(16)")
    private UUID purchasedOnOrderItemId;

    /**
     * 0-based ordinal of this card within its order item's issuance batch (a quantity-3 line yields
     * units 0, 1, 2). Combined with {@link #purchasedOnOrderItemId} in a unique index so a duplicated
     * or concurrent issuance handler cannot issue the same unit twice. Null for non-order issuance.
     */
    @Column(name = "unit_index", nullable = true)
    private Integer unitIndex;

    @Column(nullable = true)
    private Instant redeemedAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private GiftCardStatus status = GiftCardStatus.ACTIVE;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private Instant updatedAt;
}
