package backend.models.enums;

public enum VendorAuditAction {
    APPLIED,
    PROFILE_UPDATED,
    TAX_SUBMITTED,
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,
    BANKING_LINKED,
    STRIPE_ACCOUNT_CREATED,
    STRIPE_ACCOUNT_UPDATED,
    SUBMITTED_FOR_REVIEW,
    APPROVED,
    REJECTED,
    NEEDS_INFO_REQUESTED,
    SUSPENDED,
    REINSTATED,
    OFFBOARDED,
    TIER_CHANGED,
    COMMISSION_POLICY_CHANGED
}
